# Angular Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: meanstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        node-type: public
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 769566606380.dkr.ecr.ap-south-1.amazonaws.com/meanstack/frontend:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: meanstack
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
